### ISSUE TITLE
Button's icon possition to have the ability to change positions

### ISSUE THREAD

**Issue by spleafy** [prismaneui/prismane#20]
The button icon should support changing its position. From left to right side of the button.

**Comment by kavinvalli** [comment]
Oh haha, I just put up another issue like this, without seeing this. Will close that one

**Comment by kavinvalli** [comment]
Willing to work on this

**Comment by spleafy** [comment]
Thanks for creating an issue! Means a lot! Just wrote you an email, let's get in touch.
