### ISSUE TITLE
Deploy storybook to chromatic and share it

### ISSUE THREAD

**Issue by RodrigoTomeES** [prismaneui/prismane#41]
Hi,

It would be awesome to view the storybook without clone the repo,

thanks!

**Comment by spleafy** [comment]
Hello, thanks for creating an issue! I will make sure to deploy the Storybook to Chromatic as soon as possible!

**Comment by spleafy** [comment]
Hello,
The Storybook is uploaded to Chromatic. You can access it through [Prismane Storybook Chromatic](https://www.chromatic.com/start?inviteToken=chpi_5d48f5e655e9415eb8431017272d218c&appId=64c0fd7432b79714c11e2b24).

Remember that the Storybook is still in development and requires much work. I hope that I will be able to update it and provide more meaningful examples and organize it better as soon as possible!

**Comment by RodrigoTomeES** [comment]
Hi,

Great! But the deployment is not public, so I can't access. Could you make it public?

Thanks!

**Comment by spleafy** [comment]
Very sorry about that, I shared the link for collaborating, hence why it requires you to log in.

Can you try this link instead and provide feedback: [Prismane Chromatic Library](https://www.chromatic.com/library?appId=64c0fd7432b79714c11e2b24)

**Comment by RodrigoTomeES** [comment]
Thanks! Now it's work, but I think is more useful see the storybook. You can get some URL like this https://<branch>--your-app-id.chromatic.com

**Comment by spleafy** [comment]
I bet this is what you are talking about: [https://64c0fd7432b79714c11e2b24-iznprqkoge.chromatic.com](https://64c0fd7432b79714c11e2b24-iznprqkoge.chromatic.com)

**Comment by RodrigoTomeES** [comment]
Yeah, that works but that build is associated to a commit so it won't be updated with new changes. You need a link associated to a branch, because this link always have the last version of that branch.

**Comment by spleafy** [comment]
I get what you mean, It is my mistake, will publish to chromatic from master right away!

**Comment by spleafy** [comment]
Here is the link: [https://master--64c0fd7432b79714c11e2b24.chromatic.com/](https://master--64c0fd7432b79714c11e2b24.chromatic.com/). Now it works, I also added another Github action that rebuilds the storybook and publishes it to Chromatic. Can you check and update me?

**Comment by RodrigoTomeES** [comment]
I revised the link and it works. I think the two links should be in the README. But as you said before there is work in the Storybook and also in the stories because you can customize the logo, colors... of [storybook with your brand](https://storybook.js.org/docs/react/configure/theming). Besides the stories doesn't support [doc mode](https://storybook.js.org/docs/react/writing-docs/build-documentation) so I think there is some missing configuration.

If you are using Figma to design the components you can also [link figma components with storybook](https://help.figma.com/hc/en-us/articles/360045003494-Storybook-and-Figma)!.

Or even [pass a test](https://storybook.js.org/docs/react/writing-tests/introduction) from Storybook 🚀 

If you need help feel free to ask to me

**Comment by spleafy** [comment]
Hey, I have setup a brand theme for Storybook, it has been updated at Chromatic. I would appreciate any help that you can provide regarding Storybook, as this would help me a lot!

**Comment by RodrigoTomeES** [comment]
I saw it, looks amazing!

**Comment by spleafy** [comment]
Thank you! Feel free to contribute, if you have any questions, feel free to contact me! For now, I will close this issue and if you need anything, you can contact me at: martinpetrov@prismane.io. Thank you for the spent time reviewing and helping me set up Storybook, means a lot, and I appreciate the effort!
