### ISSUE TITLE
Wrong RegEx for email address

### ISSUE THREAD

**Issue by 0815fips** [prismaneui/prismane#42]
## Subdomain/Domain

The RegEx would allow domain names like `my-weird@email....address`.

### Solution

Better work with repeating capture groups here.

## TLD

This part of the RegEx specified here is too strict:
https://github.com/prismaneui/prismane/blob/3d0a71233e4a101066ad4f6891ae62c59076db1b/src/validators/validators.ts#L104C50-L104C55

Reason being that top level domains often exceed the specified 6 characters and can TECHNICALLY also only consist of a single one.

Most up-to-date source from IANA directly
http://data.iana.org/TLD/tlds-alpha-by-domain.txt

Brief description
https://en.wikipedia.org/wiki/List_of_Internet_top-level_domains

### Solution:
Replace `{2,6}` with `+`

## Thoughts on character sets in foreign languages
I'll just leave this here to think about: 钱华林@中科院.中国

**Comment by spleafy** [comment]
Thanks for submitting an issue. You are exactly right, that is a mistake that must and will be fixed immediately and will be included in the next patch version. I appreciate the effort! It means a lot!
