### ISSUE TITLE
TypeError when import Breadcumb.Item and Breadcrumb.Separator

### ISSUE THREAD

**Issue by AlbertoCruzLuis** [prismaneui/prismane#48]
`<Breadcrumb className="text-sm">
        <Breadcrumb.Item href="/">Home</Breadcrumb.Item>
        <Breadcrumb.Separator />
        <Breadcrumb.Item href="/">Products</Breadcrumb.Item>
        <Breadcrumb.Separator />
        <Breadcrumb.Item href={`/?filters=${product.category.join(",")}`}>
          {product.category.join(", ")}
        </Breadcrumb.Item>
        <Breadcrumb.Separator />
        <Breadcrumb.Item className="text-neutral-950">
          {product.name}
        </Breadcrumb.Item>
      </Breadcrumb>`

TypeError: "Type '{ children: string; href: string; }' is not assignable to type 'IntrinsicAttributes & Omit<ForwardRefExoticComponent<(Omit<{ justify?: \"center\" | \"end\" | \"start\" | \"between\" | \"around\" | \"evenly\" | undefined; align?: \"center\" | \"end\" | \"start\" | \"baseline\" | \"stretch\" | undefined; ... 6 more ...; wrap?: \"wrap\" | ... 2 more ... | undefined; } & ... 5 more ... & PrismaneComponent,...'.\n  Property 'children' does not exist on type 'IntrinsicAttributes & Omit<ForwardRefExoticComponent<(Omit<{ justify?: \"center\" | \"end\" | \"start\" | \"between\" | \"around\" | \"evenly\" | undefined; align?: \"center\" | \"end\" | \"start\" | \"baseline\" | \"stretch\" | undefined; ... 6 more ...; wrap?: \"wrap\" | ... 2 more ... | undefined; } & ... 5 more ... & PrismaneComponent,...'."

TypeError: "Property '$$typeof' is missing in type '{}' but required in type 'Omit<ForwardRefExoticComponent<Omit<BreadcrumbSeparatorProps, \"ref\"> & RefAttributes<HTMLDivElement>>, \"ref\">'."

Version: "@prismane/core": "^0.2.2",

**Comment by spleafy** [comment]
Hi, thank you for creating an issue! Will start fixing that right away!
