### ISSUE TITLE
validators match is not working properly in prismane.io website

### ISSUE THREAD

**Issue by Vishwas-75** [prismaneui/prismane#63]
When I enter "password" in password field and same "password" in repassword field.

**Expected Result**: Form should submit successfully

**Actual Result**: Getting Error "Fields must match"

<img width="521" alt="image" src="https://github.com/prismaneui/prismane/assets/69014515/fb83335f-d4d9-4e81-8c21-f96354d218a5">

**Comment by spleafy** [comment]
Hi, thanks for creating an issue! Will look right into the issue, as the problem seems to be website related.

**Comment by spleafy** [comment]
The issue has been resolved, the example is fixed, thanks again for creating an issue, it is very appreciated!
